### ISSUE TITLE
Read relative paths

### ISSUE THREAD

**Issue by LeahRoberts** [bawee/bwast#2]
Would be nice if bwast were able to read relative paths rather than having all of the necessary files in the same directory.

**Comment by bawee** [comment]
Thanks! Will work on it. In the meantime you can create symlinks using 

```
cd working_directory
ln -s ../../path/to/genbank/file.gbk .
```

**Comment by bawee** [comment]
Thanks for your feedback @LeahRoberts. I've added the ability to use sequence files that are not in the working directory/folder. Please git clone the new version and let me know how it goes when you get the chance.
